# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tDH8eT-QquJszLwwjRq5O_Dxz7dW5zfF
"""

print ("Hello World")

a=5
b=2
c=a+b
print(c)

import math
a=7.5 #основание
S=(math.sqrt(3)/4)*a**2
print(f"Пдлщадь треугольника со сторонами {a} равна {S:.3f}")

#Задаём значения переменных вручную
a=4
b=3
c=2
#Вычисляем x по формуме
x=(a**2+b**2-c**3)/2
print("Значение x=",x)

a=5
b=input("Введние значение b:") #получам второе число от пользывателя
print("Введенное значение b:", b) #Выводим введенное значение для проверки
#преобразуем b в число, чтобы можно было умножить
b=int(b)
#Вычисляем произведение
result=a*b
#Выводим результат
print("Произведение чисел:", result)

a=float(input("Введение значение a: "))
b=float(input("Введите значение b: "))
print((a+b)**2)

#Заданные значения
a=15
b=10
#Ввод значения c вручную через консоль
c=float(input("Введите значение c: "))
#Проверка деления на ноль
if c!=0:
  result=(a+b)/c
  print("Результат:", result)
else:
  print("Ошибка: деление на ноль невозможно!")

a=float(input("Введите первое число (a): "))
b=float(input("Введите второе число (b): "))
result=(a+b)**2
print(f"Формула кводрата суммы: (a+b)**2=a**2+2ab+b**2")
print(f"Подстовляем: ({a}+{b})**2={a}**2+2*{a}*{b}+{b}**2)")
print(f"\n Результат вычисления: ({a}+{b})**2={result}")

import math
a=float (input("Введите длину стороны a: "))
b=float (input("Введите длину стороны b: "))
c=float (input("Введите длину стороны c: "))
#Проверка существования треугольника
if a+b<=c or a+c<=b or b+c<=a:
  print("Треугольник с такими сторонами не существует!")
else:
  #Проверка, что треугольник неравнобедренный
  if a==b or a==c or b==c:
    print("Это не неравнобедренный треугольник")
  else:
    P=a+b+c
    p=P/2
    S=math.sqrt(p*(p-a)*(p-b)*(p-c))
    print(f"Периметр треугольника:{P:.2f}")
    print(f"Площать трееугольника: {S:.2f}")

a=float(input("Введите значение a: "))
b=float(input("Введите значение b: "))
result=((a**3+14)/5)*b
print(f"Результат выражения: {result}")
#Проверяем неравенство
if result>0:
  print("Неравенство ((a**3+14)/5)*b>0 выполняется.")
elif result==0:
  print("Выражение равное нулю.")
else:
  print("Неравенство ((a**3+14)/5)*b")

# Ввод дробных чисел для деления
num1=float(input("Введите первое дробное число "))
num2=float(input("Введите второе дробное число "))
#Проверка на дилени на ноль
if num2==0:
  print("Ошибка: деление на ноль!")
else:
#Делаем дробные числа
  result_division-num1/num2
  print(f"Результат деления: {result_division}")
#Ввод натуальных чисел
num3=int(input("Введите первое натуральное число: "))
num4=int(input("Введите второе натуральное число: "))
#Умнажение натуральных чисел
result_multiplication=num3*num4
print(f"Результат умнажения: {result_multiplication}")
#Получение остатка от деления
if num4==0:
  print("Ошибка: деление на ноль!")
else:
  result_modulo=num3%num4
  print(f"Остаток от деления: {reset_modulo}")